// data.js
export const practicas = [
    {
      empresa: 'Tech Solutions Ltda.',
      ubicacion: 'Las Condes',
      sueldo: 800000,
      tipo: 'Profesional',
      cargo: 'Desarrollador Full Stack',
      info: 'Tech Solutions Ltda. es una empresa líder en soluciones tecnológicas en Santiago, Chile. Estamos buscando un Desarrollador Full Stack para unirse a nuestro equipo altamente calificado.',
    },
    {
      empresa: 'Data Innovators S.A.',
      ubicacion: 'Providencia',
      sueldo: 750000,
      tipo: 'Profesional',
      cargo: 'Ingeniero de Datos',
      info: 'Data Innovators S.A. se especializa en análisis de datos y soluciones empresariales. Actualmente, estamos buscando un Ingeniero de Datos para unirse a nuestro equipo en Providencia.',
    },
    {
      empresa: 'WebTech Inc.',
      ubicacion: 'Ñuñoa',
      sueldo: 700000,
      tipo: 'Profesional',
      cargo: 'Diseñador UX/UI',
      info: 'WebTech Inc. es una empresa de diseño web y desarrollo de aplicaciones en Ñuñoa. Estamos buscando un Diseñador UX/UI creativo y apasionado para unirse a nuestro equipo.',
    },
    {
      empresa: 'SysAdmin Solutions',
      ubicacion: 'La Florida',
      sueldo: 150000,
      tipo: 'Industrial',
      cargo: 'Técnico de Soporte IT',
      info: 'SysAdmin Solutions se dedica al soporte técnico y soluciones informáticas. Tenemos una oportunidad para un Técnico de Soporte IT en La Florida.',
    },
    {
      empresa: 'Digital Innovations Ltda.',
      ubicacion: 'Vitacura',
      sueldo: 850000,
      tipo: 'Profesional',
      cargo: 'Analista de Datos',
      info: 'Digital Innovations Ltda. se enfoca en análisis de datos avanzados y soluciones digitales. Buscamos un Analista de Datos en Vitacura para unirse a nuestro equipo.',
    },
    {
      empresa: 'SecureNet S.A.',
      ubicacion: 'Providencia',
      sueldo: 700000,
      tipo: 'Profesional',
      cargo: 'Ingeniero de Seguridad Informática',
      info: 'SecureNet S.A. es una empresa líder en ciberseguridad. Estamos contratando un Ingeniero de Seguridad Informática en Providencia.',
    },
    {
      empresa: 'WebMasters Chile',
      ubicacion: 'Santiago Centro',
      sueldo: 600000,
      tipo: 'Industrial',
      cargo: 'Asistente de Desarrollo Web',
      info: 'WebMasters Chile se dedica al diseño y desarrollo web. Estamos en búsqueda de un Asistente de Desarrollo Web en Santiago Centro.',
    },
    {
      empresa: 'Cloud Solutions Inc.',
      ubicacion: 'Las Condes',
      sueldo: 900000,
      tipo: 'Profesional',
      cargo: 'Arquitecto de Soluciones Cloud',
      info: 'Cloud Solutions Inc. ofrece soluciones en la nube de vanguardia. Estamos contratando un Arquitecto de Soluciones Cloud en Las Condes.',
    },
    {
      empresa: 'Innovative Software Solutions',
      ubicacion: 'Ñuñoa',
      sueldo: 650000,
      tipo: 'Industrial',
      cargo: 'Técnico de Soporte Técnico',
      info: 'Innovative Software Solutions se especializa en software empresarial. Estamos buscando un Técnico de Soporte Técnico en Ñuñoa.',
    },
    {
      empresa: 'DataTech Chile Ltda.',
      ubicacion: 'La Florida',
      sueldo: 500000,
      tipo: 'Industrial',
      cargo: 'Analista de Datos Junior',
      info: 'DataTech Chile Ltda. es una empresa de análisis de datos. Tenemos una oportunidad para un Analista de Datos Junior en La Florida.',
    },
  ];